use base64::Engine;
use chrono::Utc;
use rand::{distributions::Alphanumeric, Rng};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};
use tauri::{AppHandle, Manager};
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::TcpListener;

use crate::jira::JiraClient;
use crate::settings::Settings;
use crate::state::AppState;

pub const CALLBACK_PORT: u16 = 53817;
pub const REDIRECT_URI: &str = "http://127.0.0.1:53817/callback";

/* ================= app credentials =================
 * Prefer credentials baked in at build time (from .env / env vars, never
 * committed) so end users only click "Login". Fall back to values typed in the
 * settings UI. Register the OAuth apps once; build with the .env filled in.
 *
 * EMBED_* constants are generated by build.rs into OUT_DIR/credentials.rs. */

include!(concat!(env!("OUT_DIR"), "/credentials.rs"));

fn embedded_or(embedded: Option<&str>, fallback: &str) -> String {
    match embedded {
        Some(v) if !v.trim().is_empty() => v.trim().to_string(),
        _ => fallback.trim().to_string(),
    }
}

pub fn atlassian_client_id(s: &Settings) -> String {
    embedded_or(EMBED_ATLASSIAN_CLIENT_ID, &s.atlassian_client_id)
}
pub fn atlassian_client_secret(s: &Settings) -> String {
    embedded_or(EMBED_ATLASSIAN_CLIENT_SECRET, &s.atlassian_client_secret)
}
pub fn google_client_id(s: &Settings) -> String {
    embedded_or(EMBED_GOOGLE_CLIENT_ID, &s.google_client_id)
}
pub fn google_client_secret(s: &Settings) -> String {
    embedded_or(EMBED_GOOGLE_CLIENT_SECRET, &s.google_client_secret)
}
pub fn github_client_id(s: &Settings) -> String {
    embedded_or(EMBED_GITHUB_CLIENT_ID, &s.github_client_id)
}
pub fn github_client_secret(s: &Settings) -> String {
    embedded_or(EMBED_GITHUB_CLIENT_SECRET, &s.github_client_secret)
}

/// True when this build has the provider's id+secret compiled in — the UI
/// uses this to hide the manual Client ID/Secret fields entirely.
pub fn atlassian_embedded() -> bool {
    !embedded_or(EMBED_ATLASSIAN_CLIENT_ID, "").is_empty()
        && !embedded_or(EMBED_ATLASSIAN_CLIENT_SECRET, "").is_empty()
}
pub fn google_embedded() -> bool {
    !embedded_or(EMBED_GOOGLE_CLIENT_ID, "").is_empty()
        && !embedded_or(EMBED_GOOGLE_CLIENT_SECRET, "").is_empty()
}
pub fn github_embedded() -> bool {
    !embedded_or(EMBED_GITHUB_CLIENT_ID, "").is_empty()
        && !embedded_or(EMBED_GITHUB_CLIENT_SECRET, "").is_empty()
}
const FLOW_TIMEOUT_SECS: u64 = 180;

/* ================= stored connections ================= */

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Tokens {
    pub access_token: String,
    pub refresh_token: String,
    /// unix seconds when the access token should be considered expired
    pub expires_at: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AtlassianConn {
    pub tokens: Tokens,
    pub cloud_id: String,
    pub site_url: String,
    pub site_name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GoogleConn {
    pub tokens: Tokens,
    pub email: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GitHubConn {
    pub tokens: Tokens,
    pub login: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct Connections {
    pub atlassian: Option<AtlassianConn>,
    pub google: Option<GoogleConn>,
    pub github: Option<GitHubConn>,
}

/* ---------- storage: OS keychain ----------
 * Tokens live in the OS credential store (Windows Credential Manager /
 * macOS Keychain) — encrypted by the OS and bound to the logged-in user —
 * instead of a plaintext connections.json. One entry per provider.
 *
 * The persisted copy drops the short-lived access token whenever a refresh
 * token exists: it re-mints on next use anyway, and Atlassian's JWT access
 * token alone can exceed the 2560-byte Windows credential blob limit. */

const KEYRING_SERVICE: &str = "com.wisesight.timelog";

/// Windows caps credential blobs at 2560 bytes stored as UTF-16 (≈1280 chars)
/// and an Atlassian refresh token alone is ~2000 chars — so values are split
/// across `<name>`, `<name>#2`, `<name>#3`, … entries and re-joined on read.
const KR_CHUNK_CHARS: usize = 1000;
const KR_MAX_CHUNKS: usize = 32;

fn kr_entry(name: &str) -> Result<keyring::Entry, String> {
    keyring::Entry::new(KEYRING_SERVICE, name)
        .map_err(|e| format!("เปิด OS keychain ไม่ได้: {e}"))
}

fn chunk_name(name: &str, i: usize) -> String {
    if i == 0 {
        name.to_string()
    } else {
        format!("{name}#{}", i + 1)
    }
}

fn kr_read<T: serde::de::DeserializeOwned>(name: &str) -> Option<T> {
    let mut raw = String::new();
    for i in 0..KR_MAX_CHUNKS {
        match kr_entry(&chunk_name(name, i)).ok()?.get_password() {
            Ok(part) => raw.push_str(&part),
            Err(_) => break,
        }
    }
    if raw.is_empty() {
        return None;
    }
    serde_json::from_str(&raw).ok()
}

/// Delete chunk entries from index `start` upward (stops at the first gap).
fn kr_delete_from(name: &str, start: usize) -> Result<(), String> {
    for i in start..KR_MAX_CHUNKS {
        match kr_entry(&chunk_name(name, i))?.delete_credential() {
            Ok(()) => {}
            Err(keyring::Error::NoEntry) => break,
            Err(e) => return Err(format!("ลบจาก OS keychain ไม่ได้: {e}")),
        }
    }
    Ok(())
}

fn kr_write<T: Serialize>(name: &str, value: Option<&T>) -> Result<(), String> {
    let Some(v) = value else {
        return kr_delete_from(name, 0);
    };
    let raw = serde_json::to_string(v).map_err(|e| e.to_string())?;
    let chars: Vec<char> = raw.chars().collect();
    let chunks: Vec<String> = chars
        .chunks(KR_CHUNK_CHARS)
        .map(|c| c.iter().collect())
        .collect();
    if chunks.len() > KR_MAX_CHUNKS {
        return Err("ข้อมูล token ใหญ่เกินขนาดที่ keychain รองรับ".into());
    }
    for (i, chunk) in chunks.iter().enumerate() {
        kr_entry(&chunk_name(name, i))?
            .set_password(chunk)
            .map_err(|e| format!("เขียน OS keychain ไม่ได้: {e}"))?;
    }
    // drop leftover chunks from a previously longer value
    kr_delete_from(name, chunks.len())
}

/// Slim tokens for persistence — keep only what's needed to reconnect.
fn slim(tokens: &Tokens) -> Tokens {
    if tokens.refresh_token.is_empty() {
        // no refresh token (GitHub without expiration) — the access token IS
        // the credential, keep it
        tokens.clone()
    } else {
        Tokens {
            access_token: String::new(),
            refresh_token: tokens.refresh_token.clone(),
            expires_at: 0, // forces a refresh on first use after restart
        }
    }
}

fn legacy_path(config_dir: &Path) -> PathBuf {
    config_dir.join("connections.json")
}

pub fn load(config_dir: &Path) -> Connections {
    let mut conns = Connections {
        atlassian: kr_read("atlassian"),
        google: kr_read("google"),
        github: kr_read("github"),
    };
    // migrate from the pre-keychain plaintext file, then delete it
    let legacy = legacy_path(config_dir);
    if let Some(old) = std::fs::read_to_string(&legacy)
        .ok()
        .and_then(|raw| serde_json::from_str::<Connections>(&raw).ok())
    {
        conns.atlassian = conns.atlassian.take().or(old.atlassian);
        conns.google = conns.google.take().or(old.google);
        conns.github = conns.github.take().or(old.github);
        if save(&conns).is_ok() {
            let _ = std::fs::remove_file(&legacy);
        }
    }
    conns
}

pub fn save(conns: &Connections) -> Result<(), String> {
    kr_write(
        "atlassian",
        conns
            .atlassian
            .as_ref()
            .map(|c| AtlassianConn { tokens: slim(&c.tokens), ..c.clone() })
            .as_ref(),
    )?;
    kr_write(
        "google",
        conns
            .google
            .as_ref()
            .map(|c| GoogleConn { tokens: slim(&c.tokens), ..c.clone() })
            .as_ref(),
    )?;
    kr_write(
        "github",
        conns
            .github
            .as_ref()
            .map(|c| GitHubConn { tokens: slim(&c.tokens), ..c.clone() })
            .as_ref(),
    )
}

async fn persist(app: &AppHandle) -> Result<(), String> {
    let state = app.state::<AppState>();
    let conns = state.connections.read().await.clone();
    save(&conns)
}

/* ================= helpers ================= */

fn rand_string(n: usize) -> String {
    rand::thread_rng()
        .sample_iter(&Alphanumeric)
        .take(n)
        .map(char::from)
        .collect()
}

fn parse_tokens(v: &Value, prev_refresh: Option<&str>) -> Result<Tokens, String> {
    let access = v["access_token"]
        .as_str()
        .ok_or_else(|| format!("แลก token ไม่สำเร็จ: {}", short(v)))?;
    let refresh = v["refresh_token"]
        .as_str()
        .map(|s| s.to_string())
        .or_else(|| prev_refresh.map(|s| s.to_string()))
        .unwrap_or_default();
    let expires_in = v["expires_in"].as_i64().unwrap_or(3600);
    Ok(Tokens {
        access_token: access.to_string(),
        refresh_token: refresh,
        expires_at: Utc::now().timestamp() + expires_in - 60,
    })
}

fn short(v: &Value) -> String {
    let s = v.to_string();
    s.chars().take(300).collect()
}

/// Tiny one-shot loopback HTTP server: waits for GET /callback?code=...&state=...
async fn listen_for_code(expected_state: &str) -> Result<String, String> {
    let listener = TcpListener::bind(("127.0.0.1", CALLBACK_PORT))
        .await
        .map_err(|e| format!("เปิด port {CALLBACK_PORT} ไม่ได้ (มีโปรแกรมอื่นใช้อยู่?): {e}"))?;

    let fut = async {
        loop {
            let (mut stream, _) = listener.accept().await.map_err(|e| e.to_string())?;
            let mut buf = vec![0u8; 8192];
            let n = stream.read(&mut buf).await.unwrap_or(0);
            let req = String::from_utf8_lossy(&buf[..n]).to_string();
            let path = req.split_whitespace().nth(1).unwrap_or("").to_string();

            if !path.starts_with("/callback") {
                let _ = stream
                    .write_all(b"HTTP/1.1 404 Not Found\r\nContent-Length: 0\r\n\r\n")
                    .await;
                continue;
            }

            let query = path.splitn(2, '?').nth(1).unwrap_or("");
            let mut code = None;
            let mut state = None;
            let mut error = None;
            for pair in query.split('&') {
                let (k, v) = pair.split_once('=').unwrap_or((pair, ""));
                let v = urlencoding::decode(v).map(|c| c.into_owned()).unwrap_or_default();
                match k {
                    "code" => code = Some(v),
                    "state" => state = Some(v),
                    "error" => error = Some(v),
                    _ => {}
                }
            }

            let ok = error.is_none() && code.is_some() && state.as_deref() == Some(expected_state);
            let body = if ok {
                "<html><meta charset='utf-8'><body style='font-family:sans-serif;text-align:center;padding-top:80px;background:#14161f;color:#eef'>\
                 <h2>เชื่อมต่อสำเร็จ ✓</h2><p>กลับไปที่แอป TimeLog ได้เลย</p>\
                 <script>setTimeout(()=>window.close(),1500)</script></body></html>"
            } else {
                "<html><meta charset='utf-8'><body style='font-family:sans-serif;text-align:center;padding-top:80px;background:#14161f;color:#eef'>\
                 <h2>เชื่อมต่อไม่สำเร็จ</h2><p>กลับไปลองใหม่ที่แอป TimeLog</p></body></html>"
            };
            let resp = format!(
                "HTTP/1.1 200 OK\r\nContent-Type: text/html; charset=utf-8\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{}",
                body.len(),
                body
            );
            let _ = stream.write_all(resp.as_bytes()).await;

            if let Some(err) = error {
                return Err(format!("ผู้ใช้ปฏิเสธ/เกิดข้อผิดพลาด: {err}"));
            }
            if !ok {
                return Err("callback ไม่ถูกต้อง (state ไม่ตรง)".into());
            }
            return Ok(code.unwrap());
        }
    };

    tokio::time::timeout(std::time::Duration::from_secs(FLOW_TIMEOUT_SECS), fut)
        .await
        .map_err(|_| "หมดเวลารอ login (3 นาที)".to_string())?
}

/* ================= Atlassian (Jira) ================= */

const ATLASSIAN_SCOPES: &str =
    "read:jira-work read:jira-user write:jira-work offline_access";

pub async fn connect_atlassian(app: &AppHandle) -> Result<AtlassianConn, String> {
    let state = app.state::<AppState>();
    let s = state.settings.read().await.clone();
    let client_id = atlassian_client_id(&s);
    let client_secret = atlassian_client_secret(&s);
    if client_id.is_empty() || client_secret.is_empty() {
        return Err(
            "ยังไม่มี Atlassian OAuth credentials — build โดยตั้ง TIMELOG_ATLASSIAN_CLIENT_ID/SECRET หรือกรอกในหัวข้อ 'OAuth App'".into(),
        );
    }
    let state_param = rand_string(32);
    let url = format!(
        "https://auth.atlassian.com/authorize?audience=api.atlassian.com&client_id={}&scope={}&redirect_uri={}&state={}&response_type=code&prompt=consent",
        urlencoding::encode(&client_id),
        urlencoding::encode(ATLASSIAN_SCOPES),
        urlencoding::encode(REDIRECT_URI),
        state_param
    );
    open::that(&url).map_err(|e| format!("เปิดเบราว์เซอร์ไม่ได้: {e}"))?;
    let code = listen_for_code(&state_param).await?;

    let http = reqwest::Client::new();
    let res: Value = http
        .post("https://auth.atlassian.com/oauth/token")
        .json(&json!({
            "grant_type": "authorization_code",
            "client_id": client_id,
            "client_secret": client_secret,
            "code": code,
            "redirect_uri": REDIRECT_URI,
        }))
        .send()
        .await
        .map_err(|e| e.to_string())?
        .json()
        .await
        .map_err(|e| e.to_string())?;
    let tokens = parse_tokens(&res, None)?;

    // discover the Jira site (cloud id) this token can access
    let sites: Value = http
        .get("https://api.atlassian.com/oauth/token/accessible-resources")
        .bearer_auth(&tokens.access_token)
        .send()
        .await
        .map_err(|e| e.to_string())?
        .json()
        .await
        .map_err(|e| e.to_string())?;
    // accessible-resources can list several sites/products; pick one that
    // actually granted a Jira scope (falling back to the first) so we don't
    // aim Jira calls at, say, a Confluence-only cloud id.
    let empty = vec![];
    let all = sites.as_array().unwrap_or(&empty);
    let site = all
        .iter()
        .find(|s| {
            s["scopes"]
                .as_array()
                .map(|sc| sc.iter().any(|x| x.as_str().is_some_and(|v| v.contains("jira"))))
                .unwrap_or(false)
        })
        .or_else(|| all.first())
        .ok_or("token นี้เข้าถึง Jira site ไหนไม่ได้เลย (ยังไม่ได้ให้สิทธิ์ Jira?)")?;

    let cloud_id = site["id"].as_str().unwrap_or_default().to_string();
    if cloud_id.is_empty() {
        return Err("หา Jira cloud id ไม่เจอจาก token".into());
    }

    let conn = AtlassianConn {
        tokens,
        cloud_id,
        site_url: site["url"].as_str().unwrap_or_default().to_string(),
        site_name: site["name"].as_str().unwrap_or_default().to_string(),
    };
    state.connections.write().await.atlassian = Some(conn.clone());
    persist(app).await?;
    Ok(conn)
}

/// Return an Atlassian connection with a fresh access token, refreshing if needed.
pub async fn fresh_atlassian(app: &AppHandle) -> Result<AtlassianConn, String> {
    let state = app.state::<AppState>();
    let conn = state
        .connections
        .read()
        .await
        .atlassian
        .clone()
        .ok_or("ยังไม่ได้เชื่อมต่อ Jira")?;
    if conn.tokens.expires_at > Utc::now().timestamp() {
        return Ok(conn);
    }
    let s = state.settings.read().await.clone();
    let http = reqwest::Client::new();
    let res: Value = http
        .post("https://auth.atlassian.com/oauth/token")
        .json(&json!({
            "grant_type": "refresh_token",
            "client_id": atlassian_client_id(&s),
            "client_secret": atlassian_client_secret(&s),
            "refresh_token": conn.tokens.refresh_token,
        }))
        .send()
        .await
        .map_err(|e| e.to_string())?
        .json()
        .await
        .map_err(|e| e.to_string())?;
    // Atlassian rotates refresh tokens — always persist the new one
    let tokens = parse_tokens(&res, Some(&conn.tokens.refresh_token))
        .map_err(|e| format!("ต่ออายุ Jira token ไม่ได้ ลอง Login ใหม่: {e}"))?;
    let new_conn = AtlassianConn { tokens, ..conn };
    state.connections.write().await.atlassian = Some(new_conn.clone());
    persist(app).await?;
    Ok(new_conn)
}

/* ================= Google ================= */

const GOOGLE_SCOPES: &str = "openid email https://www.googleapis.com/auth/calendar.readonly";

pub async fn connect_google(app: &AppHandle) -> Result<GoogleConn, String> {
    let state = app.state::<AppState>();
    let s = state.settings.read().await.clone();
    let client_id = google_client_id(&s);
    let client_secret = google_client_secret(&s);
    if client_id.is_empty() || client_secret.is_empty() {
        return Err(
            "ยังไม่มี Google OAuth credentials — build โดยตั้ง TIMELOG_GOOGLE_CLIENT_ID/SECRET หรือกรอกในหัวข้อ 'OAuth App'".into(),
        );
    }
    let state_param = rand_string(32);
    let verifier = rand_string(64);
    let challenge = base64::engine::general_purpose::URL_SAFE_NO_PAD
        .encode(Sha256::digest(verifier.as_bytes()));
    let url = format!(
        "https://accounts.google.com/o/oauth2/v2/auth?client_id={}&redirect_uri={}&response_type=code&scope={}&access_type=offline&prompt=consent&code_challenge={}&code_challenge_method=S256&state={}",
        urlencoding::encode(&client_id),
        urlencoding::encode(REDIRECT_URI),
        urlencoding::encode(GOOGLE_SCOPES),
        challenge,
        state_param
    );
    open::that(&url).map_err(|e| format!("เปิดเบราว์เซอร์ไม่ได้: {e}"))?;
    let code = listen_for_code(&state_param).await?;

    let http = reqwest::Client::new();
    let res: Value = http
        .post("https://oauth2.googleapis.com/token")
        .form(&[
            ("grant_type", "authorization_code"),
            ("client_id", client_id.as_str()),
            ("client_secret", client_secret.as_str()),
            ("code", code.as_str()),
            ("redirect_uri", REDIRECT_URI),
            ("code_verifier", verifier.as_str()),
        ])
        .send()
        .await
        .map_err(|e| e.to_string())?
        .json()
        .await
        .map_err(|e| e.to_string())?;
    let tokens = parse_tokens(&res, None)?;

    let userinfo: Value = http
        .get("https://openidconnect.googleapis.com/v1/userinfo")
        .bearer_auth(&tokens.access_token)
        .send()
        .await
        .map_err(|e| e.to_string())?
        .json()
        .await
        .unwrap_or(Value::Null);
    let email = userinfo["email"].as_str().unwrap_or_default().to_string();

    let conn = GoogleConn { tokens, email };
    state.connections.write().await.google = Some(conn.clone());
    persist(app).await?;
    Ok(conn)
}

/// Return a Google connection with a fresh access token, refreshing if needed.
pub async fn fresh_google(app: &AppHandle) -> Result<GoogleConn, String> {
    let state = app.state::<AppState>();
    let conn = state
        .connections
        .read()
        .await
        .google
        .clone()
        .ok_or("ยังไม่ได้เชื่อมต่อ Google Calendar")?;
    if conn.tokens.expires_at > Utc::now().timestamp() {
        return Ok(conn);
    }
    let s = state.settings.read().await.clone();
    let cid = google_client_id(&s);
    let csecret = google_client_secret(&s);
    let http = reqwest::Client::new();
    let res: Value = http
        .post("https://oauth2.googleapis.com/token")
        .form(&[
            ("grant_type", "refresh_token"),
            ("client_id", cid.as_str()),
            ("client_secret", csecret.as_str()),
            ("refresh_token", conn.tokens.refresh_token.as_str()),
        ])
        .send()
        .await
        .map_err(|e| e.to_string())?
        .json()
        .await
        .map_err(|e| e.to_string())?;
    // Google keeps the same refresh token (not returned on refresh)
    let tokens = parse_tokens(&res, Some(&conn.tokens.refresh_token))
        .map_err(|e| format!("ต่ออายุ Google token ไม่ได้ ลอง Login ใหม่: {e}"))?;
    let new_conn = GoogleConn { tokens, ..conn };
    state.connections.write().await.google = Some(new_conn.clone());
    persist(app).await?;
    Ok(new_conn)
}

/* ================= GitHub ================= */

const GITHUB_SCOPES: &str = "repo read:org read:user";
const GITHUB_TOKEN_URL: &str = "https://github.com/login/oauth/access_token";

/// GitHub OAuth tokens are non-expiring by default (no `expires_in`/refresh
/// token) unless the OAuth app opts into token expiration — handle both.
fn parse_github_tokens(v: &Value, prev_refresh: Option<&str>) -> Result<Tokens, String> {
    if let Some(err) = v["error"].as_str() {
        let desc = v["error_description"].as_str().unwrap_or("");
        return Err(format!("GitHub token error: {err} {desc}"));
    }
    let access = v["access_token"]
        .as_str()
        .ok_or_else(|| format!("แลก token ไม่สำเร็จ: {}", short(v)))?;
    let refresh = v["refresh_token"]
        .as_str()
        .map(|s| s.to_string())
        .or_else(|| prev_refresh.map(|s| s.to_string()))
        .unwrap_or_default();
    let expires_at = match v["expires_in"].as_i64() {
        Some(secs) => Utc::now().timestamp() + secs - 60,
        // no expiry advertised — treat as effectively permanent (~10 years)
        None => Utc::now().timestamp() + 10 * 365 * 24 * 3600,
    };
    Ok(Tokens {
        access_token: access.to_string(),
        refresh_token: refresh,
        expires_at,
    })
}

pub async fn connect_github(app: &AppHandle) -> Result<GitHubConn, String> {
    let state = app.state::<AppState>();
    let s = state.settings.read().await.clone();
    let client_id = github_client_id(&s);
    let client_secret = github_client_secret(&s);
    if client_id.is_empty() || client_secret.is_empty() {
        return Err(
            "ยังไม่มี GitHub OAuth credentials — build โดยตั้ง TIMELOG_GITHUB_CLIENT_ID/SECRET หรือกรอกในหัวข้อ 'OAuth App'".into(),
        );
    }
    let state_param = rand_string(32);
    let url = format!(
        "https://github.com/login/oauth/authorize?client_id={}&redirect_uri={}&scope={}&state={}",
        urlencoding::encode(&client_id),
        urlencoding::encode(REDIRECT_URI),
        urlencoding::encode(GITHUB_SCOPES),
        state_param
    );
    open::that(&url).map_err(|e| format!("เปิดเบราว์เซอร์ไม่ได้: {e}"))?;
    let code = listen_for_code(&state_param).await?;

    let http = reqwest::Client::new();
    let res: Value = http
        .post(GITHUB_TOKEN_URL)
        .header("Accept", "application/json")
        .form(&[
            ("client_id", client_id.as_str()),
            ("client_secret", client_secret.as_str()),
            ("code", code.as_str()),
            ("redirect_uri", REDIRECT_URI),
        ])
        .send()
        .await
        .map_err(|e| e.to_string())?
        .json()
        .await
        .map_err(|e| e.to_string())?;
    let tokens = parse_github_tokens(&res, None)?;

    // discover the logged-in user's login handle (needed for search qualifiers)
    let user: Value = http
        .get("https://api.github.com/user")
        .bearer_auth(&tokens.access_token)
        .header("User-Agent", "timelog")
        .header("Accept", "application/vnd.github+json")
        .send()
        .await
        .map_err(|e| e.to_string())?
        .json()
        .await
        .unwrap_or(Value::Null);
    let login = user["login"].as_str().unwrap_or_default().to_string();
    if login.is_empty() {
        return Err("อ่าน GitHub login ไม่ได้จาก token".into());
    }

    let conn = GitHubConn { tokens, login };
    state.connections.write().await.github = Some(conn.clone());
    persist(app).await?;
    Ok(conn)
}

/// Return a GitHub connection with a fresh access token, refreshing if needed.
pub async fn fresh_github(app: &AppHandle) -> Result<GitHubConn, String> {
    let state = app.state::<AppState>();
    let conn = state
        .connections
        .read()
        .await
        .github
        .clone()
        .ok_or("ยังไม่ได้เชื่อมต่อ GitHub")?;
    if conn.tokens.expires_at > Utc::now().timestamp() {
        return Ok(conn);
    }
    // expired — only OAuth apps with token expiration give us a refresh token.
    // Without one there's nothing to refresh; return as-is and let the API 401.
    if conn.tokens.refresh_token.is_empty() {
        return Ok(conn);
    }
    let s = state.settings.read().await.clone();
    let http = reqwest::Client::new();
    let res: Value = http
        .post(GITHUB_TOKEN_URL)
        .header("Accept", "application/json")
        .form(&[
            ("grant_type", "refresh_token"),
            ("client_id", github_client_id(&s).as_str()),
            ("client_secret", github_client_secret(&s).as_str()),
            ("refresh_token", conn.tokens.refresh_token.as_str()),
        ])
        .send()
        .await
        .map_err(|e| e.to_string())?
        .json()
        .await
        .map_err(|e| e.to_string())?;
    let tokens = parse_github_tokens(&res, Some(&conn.tokens.refresh_token))
        .map_err(|e| format!("ต่ออายุ GitHub token ไม่ได้ ลอง Login ใหม่: {e}"))?;
    let new_conn = GitHubConn { tokens, ..conn };
    state.connections.write().await.github = Some(new_conn.clone());
    persist(app).await?;
    Ok(new_conn)
}

/* ================= client factory ================= */

/// Build a JiraClient — prefers the OAuth connection, falls back to
/// manual basic-auth settings if OAuth was never connected.
pub async fn jira_client(app: &AppHandle) -> Result<JiraClient, String> {
    let state = app.state::<AppState>();
    let has_oauth = state.connections.read().await.atlassian.is_some();
    if has_oauth {
        let conn = fresh_atlassian(app).await?;
        return JiraClient::bearer(
            format!("https://api.atlassian.com/ex/jira/{}", conn.cloud_id),
            conn.tokens.access_token,
        );
    }
    let s = state.settings.read().await.clone();
    JiraClient::from_settings(&s).map_err(|_| {
        "ยังไม่ได้เชื่อมต่อ Jira — กด 'Login ด้วย Atlassian' ในแท็บตั้งค่า".to_string()
    })
}
